version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2
jobs:
  test:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            npm install
            npm run test:coverage
      - persist_to_workspace:
          root: /
          paths:
            - coverage
  sonarcloud:
    docker:
      - image: node:latest
    steps:
      - checkout
      - attach_workspace:
          at: /root/project
      - sonarcloud/scan
workflows:
  build_and_test:
    jobs:
      - test
      - sonarcloud:
          context:
            - sonarcloud
          requires:
            - test
