version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2
jobs:
  test:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            npm install
            npm run test:coverage
      - sonarcloud/scan
workflows:
  build_and_test:
    jobs:
      - test:
          context:
            - sonarcloud
